language: node_js
node_js:
  - 'node'

branches:
  only:
    - master
    - gh-pages

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

before_install:
  - rvm install 2.2.2

install:
  - npm install
  - gem install bundler
  - bundle install

script:
  - jekyll build
  - npm test
  - htmlproofer --assume-extension ./_site --internal-domains https://www.simonmoles.com

sudo: false

cache: 
  bundler: true
  directories:
    - $TRAVIS_BUILD_DIR/tmp/.htmlproofer
    - node_modules
