language: node_js
node_js:
  - 'node'

addons:
  apt: 
    packages:
      - curl

branches:
  only:
    - master
    - gh-pages

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - JEKYLL_ENV=production

before_install:
  - rvm install 2.2.2

install:
  - npm install
  - gem install bundler
  - bundle install

script:
  - jekyll build
  - npm test
  - htmlproofer --assume-extension ./_site --internal-domains www.simonmoles.com,simie.github.io

sudo: false

cache: 
  bundler: true
  directories:
    - $TRAVIS_BUILD_DIR/tmp/.htmlproofer

deploy:
  local_dir: "_site"
  target_branch: "gh-pages"
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master